"""FFXIV job metadata."""

JOBS: dict[str, tuple[str, str]] = {
    "Paladin": ("pld", "Tank"),
    "Warrior": ("war", "Tank"),
    "Dark Knight": ("drk", "Tank"),
    "Gunbreaker": ("gnb", "Tank"),
    "White Mage": ("whm", "Healer"),
    "Scholar": ("sch", "Healer"),
    "Astrologian": ("ast", "Healer"),
    "Sage": ("sge", "Healer"),
    "Monk": ("mnk", "Melee DPS"),
    "Dragoon": ("drg", "Melee DPS"),
    "Ninja": ("nin", "Melee DPS"),
    "Samurai": ("sam", "Melee DPS"),
    "Reaper": ("rpr", "Melee DPS"),
    "Viper": ("vpr", "Melee DPS"),
    "Beastmaster": ("bst", "Limited Job"),
    "Bard": ("brd", "Physical Ranged DPS"),
    "Machinist": ("mch", "Physical Ranged DPS"),
    "Dancer": ("dnc", "Physical Ranged DPS"),
    "Black Mage": ("blm", "Magical Ranged DPS"),
    "Summoner": ("smn", "Magical Ranged DPS"),
    "Red Mage": ("rdm", "Magical Ranged DPS"),
    "Pictomancer": ("pct", "Magical Ranged DPS"),
    "Blue Mage": ("blu", "Limited Job"),
    "Carpenter": ("crp", "Crafter"),
    "Blacksmith": ("bsm", "Crafter"),
    "Armorer": ("arm", "Crafter"),
    "Goldsmith": ("gsm", "Crafter"),
    "Leatherworker": ("ltw", "Crafter"),
    "Weaver": ("wvr", "Crafter"),
    "Alchemist": ("alc", "Crafter"),
    "Culinarian": ("cul", "Crafter"),
    "Miner": ("min", "Gatherer"),
    "Botanist": ("btn", "Gatherer"),
    "Fisher": ("fsh", "Gatherer"),
}
